
export const SET_CARDS_PRELOADED = 'SET_CARDS_PRELOADED';
export const SET_LEFT_SIDE_SELECTION = 'SET_LEFT_SIDE_SELECTION';
export const INCREASE_LEFT_SCORE = 'INCREASE_LEFT_SCORE';
export const SET_RIGHT_SIDE_SELECTION = 'SET_RIGHT_SIDE_SELECTION';
export const INCREASE_RIGHT_SCORE = 'INCREASE_RIGHT_SCORE';
export const SET_ROUND_WINNER = 'SET_ROUND_WINNER';
export const TOGGLE_CARD_REVEALED = 'TOGGLE_CARD_REVEALED';
export const TOGGLE_FULL_AUTOPLAY = 'TOGGLE_FULL_AUTOPLAY';
export const SET_GAME_OVER = 'SET_GAME_OVER';
export const RESTART = 'RESTART';
